### ISSUE TITLE
No package docker-python found

### ISSUE THREAD

**Issue by sergemastaki** [SyntropyNet/syntropy-devops-integrations#44]
I am testing integration of Syntropy Net with Ansible. So I try to run this playbook on Centos 8:
https://github.com/SyntropyNet/syntropy-devops-integrations/blob/main/nginx-and-curl-client-terraform-ansible/ansible/roles/docker/tasks/main.yml

I got that error:
fatal: [178.62.78.241]: FAILED! => {"changed": false, "failures": ["docker-python Aucune correspondance pour le paramètre: docker-python"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [192.46.220.239]: FAILED! => {"changed": false, "failures": ["No package docker-python available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

**Comment by vmag** [comment]
Seems that Centos 8 doesn't have a docker-python package, you need to edit the role task file and install docker-py with pip, not yum/dnf.

**Comment by sergemastaki** [comment]
Okay
